### ISSUE TITLE
Add Java Salted Password Hashing

### ISSUE THREAD

**Issue by kingrishabdugar** [kingrishabdugar/Green-Leaf-Gourmet#5]
The salt is random data very often used in cryptography as additional input to a hash function. Doing encryption and decryption of a String with a salt implies that you should:

1. 
2. Read an initial String.
3. Generate random bytes to be placed in the salt.
4. Use the BASE64Encoder to encode both the salt and the String and return them, as described in the encrypt(String str) method.
5. Read the encrypted String.
Finally,  Return the String representation of the byte array,

**Comment by kingrishabdugar** [comment]
@arpanbiki do ⭐the repo before you begin
Also, you can start your work from this folder :
https://github.com/kingrishabdugar/Green-Leaf-Gourmet/tree/main/src
Open using Apache NetBeans
The Dao folder stores the connection with the Database  
https://github.com/kingrishabdugar/Green-Leaf-Gourmet/blob/main/src/dao/ConnectionProvider.java

**Comment by harshitsurana** [comment]
Also, the Security Question Answer should not be saved directly in the database. It should be hashed and stored, as security question answers can be used to change the password using forgot password utility.

**Comment by kingrishabdugar** [comment]
> Also, the Security Question Answer should not be saved directly in the database. It should be hashed and stored, as security question answers can be used to change the password using forgot password utility.



Absolutely correct 💯, will fix both of these asap
